### ISSUE TITLE
how to connect to server?

### ISSUE THREAD

**Issue by appleplants** [jopeo/Battle-Anki#2]
hi! i'm so sorry to bother you, but I just downloaded battleanki and have no idea how to config the add-on. i went and set the "use_deck" parameter as my deck name, but i'm not sure where to add the ip and port. when i opened the add-on, there was nobody on the server but me, so i'm assuming i wasn't able to connect to the right server. may i ask where to config the ip and port? should i use my own ip address? are we only able to battle ppl who are nearby? i'm sorry if this has already been answered, and thank you so much for your help!

**Comment by jopeo** [comment]
Hello, so sorry for the delay and for the problem you had! You do not need to configure the server - this is all done automatically now. The original Battle Anki server is now public. The only thing you will need to do is configure your "use_deck", and then you're all set! I have updated the add-on page accordingly, and again I apologize for the inconvenience! If no one showed up in the "Battle Anki" window, then unfortunately no one was on the server.

You can battle anyone in the world, and even people in another world if they have internet - there are no geographical limitations!

Best Regards from the creator of Battle Anki,

-jopeo
